# - name: Add user group
#   group:
#     name: redis
#     gid: 667
#     system: yes

# - name: Add user
#   user:
#     name: redis
#     group: redis
#     uid: 667
#     system: yes
#     shell: /usr/sbin/nologin
#     create_home: no

- name: Create installation directory
  file:
    path: '/fluentd/etc'
    state: directory
    # owner: redis
    # group: redis
    # recurse: yes
  # with_nested: 
  # - ['{{ redis_instance_port }}','{{ redis_sentinel_port }}']
  # - ['conf', 'log', 'run', 'data']

- name: Copy file with owner and permissions
  copy:
    src: ./efkstack/fluentd/conf/fluentd.conf
    dest: '/fluentd/etc'
    # owner: foo
    # group: foo
    mode: '0644'

- name: Copy file with owner and permissions
  copy:
    src: ./efkstack
    dest: '{{ efk_install_dir }}'
    # owner: foo
    # group: foo
    mode: '0644'

