---

- name: Create installation directory
  file:
    path: '/fluentd/etc'
    state: directory

# - name: Copy file with owner and permissions
#   copy:
#     src: ./efkstack/fluentd/conf/fluentd.conf
#     dest: '/fluentd/etc'
#     mode: '0644'

- name: Copy file with owner and permissions
  copy:
    src: ./efkstack
    dest: '{{ efk_install_dir }}'
    mode: '0644'

...
